#!/usr/bin/env python3

IMAGE_WIDTH_IDENTIFY = 64
IMAGE_HEIGHT_IDENTIFY = 64
IMAGE_WIDTH_REMOVE = 683
IMAGE_HEIGHT_REMOVE = 384
CHANNELS = 3
PREPROCESSED_LAYERS = 1
EPOCHS = 10
PRETRAIN_EPOCHS = 2
BATCH_SIZE = 500
BATCH_SIZE_VALIDATION = 100
STEPS_PER_EPOCH = 100
CATEGORIES = 2
OPACITY_MIN = 0.3
OPACITY_MAX = 0.8
OPACITY_PRETRAIN_MIN = 0.7
OPACITY_PRETRAIN_MAX = 0.8
BOX_SIZE_REL = 0.2
STRIDE_WIDTH = 8
STRIDE_HEIGHT = 8
